from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('register/verify/', views.register_verify, name='register_verify'),
    path('register/activate/', views.register_activate, name='register_activate'),
    path('', views.home, name='home'),
    path('add_student/', views.add_student, name='add_student'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('train/', views.train, name='train'),
    path('upload_attendance/', views.upload_attendance, name='upload_attendance'),
    path('manual_attendance/', views.manual_attendance, name='manual_attendance'),
    path('attendance_list/', views.attendance_list, name='attendance_list'),
    path('attendance_list/', views.attendance_list, name='attendance_list'),
    path('student/<int:student_id>/', views.student_attendance, name='student_attendance'),
    path('notifications/get/', views.get_notifications, name='get_notifications'),
    path('notifications/read/<int:notif_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('live_attendance/', views.live_attendance, name='live_attendance'),
    path('process_live_frame/', views.process_live_frame, name='process_live_frame'),
    path('manage_students/', views.manage_students, name='manage_students'),
    path('download_attendance/', views.download_attendance, name='download_attendance'),
    path('edit_student/<int:student_id>/', views.edit_student, name='edit_student'),
    path('delete_student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('manage_teachers/', views.manage_teachers, name='manage_teachers'),
    path('edit_teacher/<int:teacher_id>/', views.edit_teacher, name='edit_teacher'),
    path('delete_teacher/<int:teacher_id>/', views.delete_teacher, name='delete_teacher'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('change_password/', views.change_password, name='change_password'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('manage_teacher_subjects/', views.manage_teacher_subjects, name='manage_teacher_subjects'),
    path('assign_teacher_subject/', views.assign_teacher_subject, name='assign_teacher_subject'),
    path('edit_teacher_subject/<int:subject_id>/', views.edit_teacher_subject, name='edit_teacher_subject'),
    path('delete_teacher_subject/<int:subject_id>/', views.delete_teacher_subject, name='delete_teacher_subject'),
    path('store/', views.teacher_store, name='teacher_store'),
    path('store/cancel/<int:request_id>/', views.cancel_assessment_request, name='cancel_assessment_request'),
    path('store/review/<int:request_id>/', views.review_assessment_request, name='review_assessment_request'),
    path('store/accessory/cancel/<int:request_id>/', views.cancel_accessory_request, name='cancel_accessory_request'),
    path('store/accessory/review/<int:request_id>/', views.review_accessory_request, name='review_accessory_request'),
    # Course Materials
    path('teacher_materials/', views.teacher_materials, name='teacher_materials'),
    path('teacher_materials/delete/<int:material_id>/', views.delete_material, name='delete_material'),
    path('student_materials/', views.student_materials, name='student_materials'),
    path('student_materials/submit/<int:material_id>/', views.submit_assignment, name='submit_assignment'),
    path('student_materials/request_late/<int:material_id>/', views.request_late_submission, name='request_late_submission'),
    path('teacher_materials/submissions/<int:material_id>/', views.view_submissions, name='view_submissions'),
    path('teacher_materials/grade/<int:submission_id>/', views.grade_submission, name='grade_submission'),
    path('teacher_materials/resolve_late/<int:request_id>/', views.resolve_late_request, name='resolve_late_request'),
    # Store Management (Admin)
    path('store_dashboard/', views.admin_store_dashboard, name='admin_store_dashboard'),
    path('store_staff/add/', views.add_store_staff, name='add_store_staff'),
    path('store_staff/edit/<int:staff_id>/', views.edit_store_staff, name='edit_store_staff'),
    path('store_staff/delete/<int:staff_id>/', views.delete_store_staff, name='delete_store_staff'),
    path('store_request/update/<int:request_id>/', views.update_store_request, name='update_store_request'),
    # Store Workflow
    path('store_request/submit/', views.submit_store_request, name='submit_store_request'),
    path('store_request/mine/', views.my_store_requests, name='my_store_requests'),
    path('store_request/confirm/<int:request_id>/', views.teacher_confirm_receipt, name='teacher_confirm_receipt'),
    path('hod/store/', views.hod_store_requests, name='hod_store_requests'),
    path('hod/store/review/<int:request_id>/', views.hod_review_store_request, name='hod_review_store_request'),
    path('store_head/', views.store_head_dashboard, name='store_head_dashboard'),
    path('store_head/assign/<int:request_id>/', views.assign_store_request, name='assign_store_request'),
    path('store_staff/tasks/', views.store_staff_tasks, name='store_staff_tasks'),
    path('store_staff/respond/<int:request_id>/', views.store_staff_respond, name='store_staff_respond'),
    # Store Notifications API
    path('store_notifications/get/', views.get_store_notifications, name='get_store_notifications'),
    path('store_notifications/read/<int:notif_id>/', views.mark_store_notification_read, name='mark_store_notification_read'),
    path('store_notifications/read_all/', views.mark_all_store_notifications_read, name='mark_all_store_notifications_read'),
    
    # Class Coordinator URLs
    path('student/applications/', views.student_applications, name='student_applications'),
    path('coordinator/dashboard/', views.coordinator_dashboard, name='coordinator_dashboard'),
    path('coordinator/application/resolve/<int:app_id>/', views.coordinator_resolve_application, name='coordinator_resolve_application'),
    path('coordinator/export/excel/<int:coord_id>/', views.export_coordinator_attendance_excel, name='export_coordinator_attendance_excel'),
]
