# Generated by Django 5.2.8 on 2025-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_admin_teacher_student_plain_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
