# Generated by Django 5.2.8 on 2025-12-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_attendancerecord_date_notification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together=set(),
        ),
    ]
