# Generated by Django 5.2.8 on 2025-12-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_attendancerecord_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachersubject",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
