# Generated by Django 5.2.8 on 2025-12-12 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_teachersubject_end_time_teachersubject_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="time",
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
