# Generated by Django 5.2.8 on 2026-04-28 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_assessmentrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessory_type",
                    models.CharField(
                        choices=[
                            ("pen", "Pen"),
                            ("marker", "Marker / Whiteboard Marker"),
                            ("duster", "Duster / Board Eraser"),
                            ("chalk", "Chalk"),
                            ("board_cleaner", "Board Cleaner / Spray"),
                            ("eraser", "Eraser"),
                            ("stapler", "Stapler"),
                            ("tape", "Tape / Adhesive"),
                            ("scissors", "Scissors"),
                            ("ruler", "Ruler / Scale"),
                            ("notebook", "Notebook / Register"),
                            ("printer_paper", "Printer Paper / A4 Sheets"),
                            ("projector_remote", "Projector Remote"),
                            ("pointer", "Laser Pointer"),
                            ("other", "Other"),
                        ],
                        default="pen",
                        max_length=30,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High / Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any extra details about the request"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_remarks",
                    models.TextField(
                        blank=True, help_text="Admin response or remarks", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
