# Generated by Django 5.2.8 on 2026-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_teacherprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE", "Computer Science & Engineering"),
                    ("IT", "Information Technology"),
                    ("ECE", "Electronics & Communication"),
                    ("EE", "Electrical Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CE", "Civil Engineering"),
                    ("AIDS", "AI & Data Science"),
                    ("AIML", "AI & Machine Learning"),
                    ("other", "Other"),
                ],
                default="CSE",
                max_length=10,
            ),
        ),
    ]
