# Generated by Django 5.2.8 on 2026-04-29 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_storerequest_storerequestitem_storestaff_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storerequest",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storerequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to="core.storestaff",
            ),
        ),
        migrations.AddField(
            model_name="storerequest",
            name="expected_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storerequest",
            name="hod_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storerequest",
            name="hod_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_approved_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storerequest",
            name="hod_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="storerequest",
            name="staff_response",
            field=models.TextField(blank=True, help_text="Store staff response/notes"),
        ),
        migrations.AlterField(
            model_name="storerequest",
            name="remarks",
            field=models.TextField(blank=True, help_text="Store Head remarks"),
        ),
        migrations.AlterField(
            model_name="storerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_hod", "Awaiting HOD Approval"),
                    ("hod_rejected", "Rejected by HOD"),
                    ("pending_store", "Awaiting Store Head"),
                    ("assigned", "Assigned to Staff"),
                    ("partial", "Partially Fulfilled"),
                    ("fulfilled", "Fully Fulfilled"),
                    ("rejected", "Rejected by Store"),
                ],
                default="pending_hod",
                max_length=20,
            ),
        ),
    ]
