# Generated by Django 5.2.8 on 2026-04-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_storerequest_assigned_at_storerequest_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storerequest",
            name="teacher_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storerequest",
            name="teacher_remarks",
            field=models.TextField(blank=True, help_text="Teacher remarks on receipt"),
        ),
        migrations.AddField(
            model_name="storerequestitem",
            name="quantity_received",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="storerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_hod", "Awaiting HOD Approval"),
                    ("hod_rejected", "Rejected by HOD"),
                    ("pending_store", "Awaiting Store Head"),
                    ("assigned", "Assigned to Staff"),
                    ("delivered", "Delivered by Staff (Awaiting Confirmation)"),
                    ("partial", "Partially Fulfilled"),
                    ("fulfilled", "Fully Fulfilled"),
                    ("rejected", "Rejected by Store"),
                ],
                default="pending_hod",
                max_length=20,
            ),
        ),
    ]
