# Generated by Django 5.2.8 on 2026-04-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_storenotification"),
        ("core", "0018_storerequest_teacher_confirmed_at_and_more"),
    ]

    operations = []
