# Generated by Django 5.2.8 on 2026-05-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_merge_20260501_0045"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="storenotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[("assignment", "Assignment"), ("notes", "Notes")],
                        default="assignment",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="course_materials/")),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("section", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
