# Generated by Django 4.2.16 on 2026-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_studentsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
