# Generated by Django 4.2.16 on 2026-05-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_latesubmissionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
    ]
