# Generated by Django 4.2.16 on 2026-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_studentapplication_classcoordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
